Comment on test failure (unsure syntax)

diff --git a/.github/workflows/userprofile.yml b/.github/workflows/userprofile.yml
--- a/.github/workflows/userprofile.yml
+++ b/.github/workflows/userprofile.yml
@@ -17,7 +17,7 @@ defaults:
     working-directory: apis/userprofile
 
 jobs:
-  build:
+  test:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v3
@@ -27,4 +27,32 @@ jobs:
           node-version: 12.x
       - run: npm ci
       - run: npm run build --if-present
-      - run: npm test
+      - id: npm_test
+        run: npm test
+        continue-on-error: true
+      - name: 'comment if failure'
+        if: github.event_name == 'pull_request' && steps.npm_test.outcome != 'success'
+          github.issues.createComment({
+            issue_number: context.issue.number,
+            owner: context.repo.owner,
+            repo: context.repo.repo,
+            body: |
+              ### Unit Test `failure`
+              <details>
+              <summary>Workflow details</summary>
+
+              Workflow name: `${{ github.workflow }}`
+              Action: `${{ github.event_name }}`
+              Job: `${{ github.job }}`
+              PR: #${{ github.event.number }}
+              </details>
+
+              Test details: [Run #${{ github.run_id }}](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})
+              Pusher: @${{ github.actor }}
+          })
+          run: exit 1
+      - name: 'create bug if failure'
+        if: github.event_name == 'workflow_dispatch' && steps.npm_test.outcome != 'success'
+          # create a bug
+          github_cli(create bug)
+          run: exit 1
